include/mpd/tag.h
src/tag.c

Allows the user to use the AlbumSort tag, simlar to ArtistSort and
AlbumArtistSort.  This allows a user to ignore "The" or "A(n)", preventing having essentially a subsort with this words.

Added AlbumSort compatibility

---

meson.build

Fixes the error "Tried to form an absolute path to a source dir. You
should not do that but use relative paths instead."

meson.build: fix build with meson > 0.38.1

---

include/mpd/async.h
src/async.c
src/socket.c
src/socket.h

Provide the result of setsockopt() for the caller of
mpd_async_set_keepalive()

async: unveil status of mpd_async_set_keepalive operation

---

include/mpd/async.h

Hello,
The mentioned mpd_async_is_alive() function has been removed a long time ago; thus, update the mpd_async_get_error_message() description to use the appropriate function: mpd_async_get_error().
The alive function/flag was removed with the commit d77247c.

async: fix mpd_async_get_error_message description

---

include/mpd/async.h

Hello,
this commit clarifies two things about mpd_async_send_command: (i) the args list expects only one datatype (const char *) and (ii) the function can fail due to a previous async operation that may be unrelated to the buffer status.

async: clarify mpd_async_send_command description

---

include/mpd/capabilities.h

Update documentation to employ updated function names
commit 508c45bc9dda0671a1456af9ce4c02ad45413d84 revised capabilities
mpid_send_* function names and
commit 36736c87b5cd11e7da8b33213917d39a2e9144da revised capabilities
mpd_recv_* function names

capabilities: revised documentation

---

NEWS

commit 1f57d2206fd7a9bd7824b1d5151511eacf7dce26
added support for MPD_TAG_LABEL and MPD_MUSICBRAINZ_WORKID
---
i forgot to change the NEWS file for commit 1f57d2206fd7a9bd7824b1d5151511eacf7dce26

news: add new tag types supported by libmpdclient

---

NEWS
include/mpd/connection.h
src/connection.c

Provide the result of setsockopt() for the caller of
mpd_connection_set_keepalive()
---
update mpd_connection_set_keepalive() since commit f7592ba8130c9c3f1f654b3bd2f9381791679036 changed mpd_async_set_keepalive() from void to bool

connection: unveil status of mpd_connection_set_keepalive operation

---

include/mpd/database.h

Hello,
commit 7290f779 suggested mpd_recv_entity() for mpd_send_list_all and mpd_send_list_all_meta; but it didn't for mpd_send_list_all. I imagine that this was an oversight?
Additionally, i've tried to correct some other minor mistakes

database: minor fixes for documentation

---

include/mpd/fingerprint.h

Update documentation to inform the user that the fingerprint 
API requires libmpdclient 2.17 and MPD 0.22.
Describe the uri parameter for the fingerprint API.
---
Hello,
i did not found if the chromaprint fingerprint uses a fixed-size string or not; if it is so, the user could avoid the undefined behavior of an insufficient buffer size.

fingerprint: inform libmpdclient and MPD version requirement

---

include/mpd/entity.h

Rectify the documentation of the mpd_entity_get_playlist() return type
from mpd_directory to mpd_playlist for mpd_entity_get_playlist().
Additionally, modify three instances of 'of' to 'if'.

entity: fix documentation of return type for mpd_entity_get_playlist

---

include/mpd/async.h
include/mpd/idle.h
include/mpd/mount.h
include/mpd/output.h
include/mpd/player.h
src/list.c
src/player.c

Hello,
this is a multi-commit series for improving the documentation of multiple "subsystems" of libmpdclient
most of the fixes are minor, except for the player subsystem.
here's a summary:
idle subsystem:
https://github.com/MusicPlayerDaemon/libmpdclient/commit/fe7fe6077675a4f7e980f3a911e66eebbc24ad3a: minor update adding missing parameters/return types for idle
https://github.com/MusicPlayerDaemon/libmpdclient/commit/8cc2ee8ed434cf5cb594fef6582234889eb09dc2: minor typo in `mpd_recv_idle()` for idle subsystem
list subsystem:
https://github.com/MusicPlayerDaemon/libmpdclient/commit/df4b815f74e68160fdc3ecb6b0a2275787866e42: clarify why `mpd_command_list_end()` sets `sending_command_list` to `true`
mount subsystem:
https://github.com/MusicPlayerDaemon/libmpdclient/commit/34d8b547c69f70788675 …

Documentation updates for async, idle, list, mount, output and player subsystems

---

include/mpd/async.h
include/mpd/recv.h
libmpdclient.ld
src/async.c
src/binary.h
src/recv.c
src/sync.c
src/sync.h

This pull requests adds following functions:
mpd_async_recv_binary -> works like mpd_async_recv_line
mpd_sync_recv_binary -> works like mpd_sync_recv_line
mpd_recv_binary -> works like mpd_recv_pair

adds low level functions to support binary data

---

include/mpd/async.h
include/mpd/playlist.h
include/mpd/queue.h
include/mpd/recv.h
include/mpd/search.h
include/mpd/song.h
include/mpd/stats.h
include/mpd/status.h
include/mpd/sticker.h
include/mpd/tag.h

Hello, this is a multi-commit series to improve the documentation of multiple 
libmpdclient APIs; the subsystems are: async, playlist, queue, recv, search, 
song, stats, status, tag, and sticker.
32f5550c267aaa9834e3d96e553c4c2a813541e9, 05e60dcc56189ad47d52f5e01546275447b3a1c0, 3bb8b43d344bb5ab2ba42f9a333054af18604286: identify functions/tags that require libmpdclient 2.17
16821a2ac86699e6e516c4831ed95fd1db9fdc25: identifies another function added to libmpdclient 2.17
d945a8b3ec2be80911712a8c293ab410770ad12e: completes the API documentation for the playlist API
d945a8b3ec2be80911712a8c293ab410770ad12e: completes the API documentation for the queue API
28a918c36ee79af56a383433990de3b1cf8531da: link the queue API to the explanation on `mpd/playlist.h` for the preference of manipulation …

improve documentation of multiple libmpdclient functions

---

src/connection.c
src/settings.c
src/song.c
src/status.c

Hello,
this series of commits address out of memory (OOM) events in some of libmpdclient functions.
96eb06f18034aa8e3279b14bee797b7f82d356f7: guard against an OOM event in `mpd_connection_new()`
e7c4c125d093f322f5219ee213a2693d605af4df: refactor internal functions of the settings API so that we can catch OOM events during the parse of host/password (`mpd_settings_new()`). Previously, some OOM events were silently ignored.
5c751a761ec9f71a43ee0e41cfff3208f31a58b8: adds asserts to debug builds for the song API
20866c98385b740a74f6f3fed4dfc7f86ebebb83: adds asserts to debug builds for the status API

Patches for out of memory events

---

NEWS
include/mpd/player.h
include/mpd/status.h
libmpdclient.ld
src/player.c
src/status.c

Support "oneshot" single mode in libmpdclient 2.18. Oneshot allows MPD to
transition automatically from "on" to "off" if the current song has
finished and another song is present in the current playlist.

status: add support for "oneshot" single mode

---

src/settings.c

Fix off-by-one write in hostname for mpd_parse_host_password()
Address issue reported by Leo Nikkila (@Inikkila) [1]
[1] https://github.com/MusicPlayerDaemon/libmpdclient/issues/52

settings: fix off-by-one write in hostname

---

NEWS
include/mpd/idle.h
include/mpd/playlist.h
include/mpd/replay_gain.h

Hello,
this minor patch identifies libmpdclient version requirement for newly added functions to version 2.19

Add missing API doc for libmpdclient 2.19 functions

---

doc/meson.build
meson.build

When building libmpdclient as a subproject, using the function `meson.source_root()` will return the path of the global source root directory instead of the subproject source root directory. Using `meson.project_source_root()` will produce the correct behavior. Also, `meson.source_root()` has been [deprecated in Meson version 0.56.0](https://mesonbuild.com/Reference-manual_builtin_meson.html#mesonsource_root).
**Note:** This commit bumps the required minimum Meson version to 0.56.0. If this isn't acceptable for the project at this time, it could be changed to conditionally use this function depending on the Meson version being used ([like the current build defintion does for `compiler.has_link_argument()`](https://github.com/MusicPlayerDaemon/libmpdclient/blob/e67883d9a07a7d3cf760bfd24f539 …

Replace meson.source_root() with meson.project_source_root()

---

include/mpd/albumart.h
include/mpd/readpicture.h

This PR modifies the language of the albumart/readpicture command comments to state that it's a requirement of the command to have a buffer size at least equal to the binary limit.
Ran into a documentation issue for the `albumart` and `readpicture` commands that blocked me for a few hours. Namely if you provide a buffer that's smaller than the binary limit, the return value from `mpd_recv_albumart`, `mpd_run_albumart`, `mpd_recv_readpicture`, and `mpd_run_readpicture` will be `-1`. The functions seem to respond correctly if the buffer size is greater than the binary limit.
While I suspect there's an underlying code issue, I'm unfamiliar with the layers of MPD and libmpdclient to figure out where it exists. I don't think I missed any spots, please let me know if there's any …

Clarified documentation for albumart/readpicture commands

---

src/connection.c
src/internal.h
src/settings.c

So, this is a rework of the retry logic in `mpd_connection_new()`, with the eventual goal of adding support for a XDG_RUNTIME_DIR based default socket location. It would also be useful for other alternative defaults added in the future.
The idea is simple: turn the settings structure into a linked list. If a socket connection fails, try the next entry in the list.
---
As this list is built ONLY when no explicit settings are provided, there is a slight change in behaviour - if a user _explicitly_ sets a host value (either via argument or via MPD_HOST) equal in value to DEFAULT_SOCKET, no attempt at connecting to DEFAULT_HOST occurs. In my eyes this is a bugfix (why should an explicit setting trigger different behaviour because it happens to be equal to the default setting?).
I have tested …

Refactor connection retry code.

---

NEWS
include/mpd/tag.h
src/tag.c

Implements the client support for the `ShowMovement` tag introduced in [PR](https://github.com/MusicPlayerDaemon/MPD/pull/2085) / [commit](e3809bd4f07db1a1922e74756e603120430bc82f).

feat: Add ShowMovement Tag
